DONE: feat(ComplaintHandlingService): Feign client для ComplaintHandlingService #93
kostua16/TLT_NC_AMA_2021 pull request #100
Opened 2022-03-23 14:45 UTC by DcoldD

feat(ComplaintHandlingService): Feign client для ComplaintHandlingService #93

2022-03-23 14:47 UTC, Spec163 commented on projects/hotel_automation_project/common/pom.xml
> +            <version>3.1.1</version>
move version to properties

2022-03-25 13:27 UTC, kostua16 commented
Проект успешно собрался для коммита 679c0e7a34a14f6d3a5af6bf214d6362656098ac. Разрешение получено.

2022-03-25 13:28 UTC, kostua16 commented
Проект успешно собрался для коммита 679c0e7a34a14f6d3a5af6bf214d6362656098ac. Разрешение получено.

2022-03-25 15:02 UTC, Spec163 requested changes

2022-03-25 15:02 UTC, Spec163 commented on projects/hotel_automation_project/complaint_handling_service/src/main/java/nc/unc/ama/complaint_handling_service/controllers/ComplaintController.java
> +        for(Complaint complaint:complainList){
`for(Complaint complaint: complaintService.getAllComplaints())`

2022-03-25 15:02 UTC, Spec163 commented on projects/hotel_automation_project/complaint_handling_service/src/main/java/nc/unc/ama/complaint_handling_service/controllers/ComplaintController.java
> +        for(Complaint complaint:complainList){
`for(Complaint complaint: staffMemberDTO.getStaffMemberId()`

2022-03-25 15:02 UTC, Spec163 commented on projects/hotel_automation_project/complaint_handling_service/src/main/java/nc/unc/ama/complaint_handling_service/services/ComplaintService.java
> +
add `@Transactional`

2022-04-01 12:26 UTC, kostua16 commented
Проект успешно собрался для коммита 4265e6c25475732e7dc6e9990e3fca7fb05888f8. Разрешение получено.

2022-04-01 14:17 UTC, Fiyri44 requested changes

2022-04-01 14:17 UTC, Fiyri44 commented on projects/hotel_automation_project/common/src/main/java/nc/unc/ama/complaint_handling_service/dto/ComplaintDTO.java
> +    }
Привести к общему виду

2022-04-01 14:17 UTC, Fiyri44 commented on projects/hotel_automation_project/complaint_handling_service/src/main/java/nc/unc/ama/complaint_handling_service/controllers/ComplaintController.java
> +    @GetMapping
@GetMapping(path = "?")

2022-04-01 14:17 UTC, Fiyri44 commented on projects/hotel_automation_project/complaint_handling_service/src/main/java/nc/unc/ama/complaint_handling_service/services/ComplaintService.java
>          return complaintRepo.findById(complaintId).get();
Optional

2022-04-02 20:17 UTC, kostua16 commented
Проект успешно собрался для коммита 343c1482d4573defdae8809b62ae2dc0a0b1a3be. Разрешение получено.

2022-04-03 13:04 UTC, Fiyri44 approved these changes

2022-04-03 15:48 UTC, Spec163 approved these changes

2022-04-03 15:49 UTC, kostua16 commented
Проект успешно собрался для коммита 8ee9d254ec28a1427c4c76cc4ad8fa764238344c. Разрешение получено.

2022-04-03 15:50 UTC, merged