feat: Entity Bills #106
kostua16/TLT_NC_AMA_2021 pull request #129
Opened 2022-04-15 12:59 UTC by Fiyri44

2022-04-15 13:00 UTC, kostua16 commented
Проект успешно собрался для коммита dbb6734c3d5642f5f505b1f3fe7381be0e0529a0. Разрешение получено.

2022-04-15 13:01 UTC, kostua16 commented
Проект успешно собрался для коммита dbb6734c3d5642f5f505b1f3fe7381be0e0529a0. Разрешение получено.

2022-04-15 14:07 UTC, kostua16 commented
Проект успешно собрался для коммита dbb6734c3d5642f5f505b1f3fe7381be0e0529a0. Разрешение получено.

2022-04-15 14:08 UTC, kostua16 commented
Проект успешно собрался для коммита dbb6734c3d5642f5f505b1f3fe7381be0e0529a0. Разрешение получено.

2022-04-18 07:22 UTC, Spec163 approved these changes

2022-04-20 14:19 UTC, kostua16 commented
После коммита b1b47da6e5557953d8b13b7a59295f3c0db574fb проект невозможно собрать. Разрешение отозвано, требуются исправления.

2022-04-20 14:20 UTC, kostua16 commented
После коммита b1b47da6e5557953d8b13b7a59295f3c0db574fb проект невозможно собрать. Разрешение отозвано, требуются исправления.

2022-04-22 13:03 UTC, kostua16 commented
Проект успешно собрался для коммита 2ba5f5866333f5fdf54bc307f83c2440db1adf00. Разрешение получено.

2022-04-22 13:04 UTC, kostua16 commented
Проект успешно собрался для коммита 2ba5f5866333f5fdf54bc307f83c2440db1adf00. Разрешение получено.

2022-04-22 13:57 UTC, Spec163 requested changes

2022-04-22 13:57 UTC, Spec163 commented on projects/hotel_automation_project/guest_service/src/main/java/nc/unc/ama/guest_service/entity/OccupiedRooms.java
> +import javax.persistence.*;
use single imports instead of `*`

2022-04-29 12:54 UTC, kostua16 requested changes

2022-04-29 12:54 UTC, kostua16 commented on projects/hotel_automation_project/common/src/main/java/nc/unc/ama/complaint_handling_service/dto/OccupiedRoomsREST.java
> +@ConditionalOnProperty()
Вернуть параметры аннотаций

2022-04-29 12:54 UTC, kostua16 commented on projects/hotel_automation_project/complaint_handling_service/src/main/java/nc/unc/ama/complaint_handling_service/controllers/OccupiedRoomsControllerImpl.java
> -public class OccupiedRoomsControllerImpl implements OccupiedRoomsREST {
Вернуть наследование интерфейса, методы и поля сервиса и клиента должны совпадать

2022-04-29 12:54 UTC, kostua16 commented on projects/hotel_automation_project/guest_service/src/main/java/nc/unc/ama/guest_service/dao/OcRoomsRepo.java
> +public interface OcRoomsRepo extends JpaRepository<OccupiedRooms,Long> {
`@Repository`

2022-05-23 13:18 UTC, closed without merging