feat(BookingService): Guest контролеры, сервисы, репозиторий, entity, DTO #133
kostua16/TLT_NC_AMA_2021 pull request #136
Opened 2022-04-20 13:48 UTC by DcoldD

2022-04-20 13:51 UTC, kostua16 commented
Проект успешно собрался для коммита 8cfd27f5a08b333f9458101874eab93cb0be7880. Разрешение получено.

2022-04-20 13:52 UTC, kostua16 commented
Проект успешно собрался для коммита 8cfd27f5a08b333f9458101874eab93cb0be7880. Разрешение получено.

2022-04-21 17:57 UTC, Spec163 requested changes

2022-04-21 17:57 UTC, Spec163 commented on projects/hotel_automation_project/booking_service/src/main/java/nc/unc/ama/booking_service/services/GuestService.java
> +    public Guest getRegisteredUsers (String password, String username, Long registrationId)
why are you expecting username and password if you are not going to use them?

2022-04-21 17:57 UTC, Spec163 commented on projects/hotel_automation_project/booking_service/src/main/java/nc/unc/ama/booking_service/services/GuestService.java
> +        return guestRepo.findById(registrationId).orElseThrow(() -> new NullPointerException());
better throw custom exception (extended RuntimeException) instead of NPE.
And where are you catch this exception? (I don't see any exception handler).

2022-04-21 17:57 UTC, Spec163 commented on projects/hotel_automation_project/booking_service/src/main/java/nc/unc/ama/booking_service/services/GuestService.java
> +        return guestRepo.findById(registrationId).orElseThrow(() -> new NullPointerException());
better throw custom exception (extended RuntimeException) instead of NPE.
And where are you catch this exception? (I don't see any exception handler).

2022-04-21 17:57 UTC, Spec163 commented on projects/hotel_automation_project/booking_service/src/main/java/nc/unc/ama/booking_service/services/GuestService.java
> +        return guestRepo.findById(guestId).get();
check npe (use orElse or orElseThrow)

2022-04-21 17:57 UTC, Spec163 commented on projects/hotel_automation_project/booking_service/src/main/java/nc/unc/ama/booking_service/services/GuestService.java
> +        return guestRepo.findById(guestId).get();
check npe (use orElseGet or orElseThrow)

2022-04-21 17:57 UTC, Spec163 commented on projects/hotel_automation_project/booking_service/src/main/java/nc/unc/ama/booking_service/services/GuestService.java
> +    public void createGuest(Guest guest) {
`@Transactional`

2022-04-21 17:57 UTC, Spec163 commented on projects/hotel_automation_project/booking_service/src/main/java/nc/unc/ama/booking_service/services/GuestService.java
> +    public void createGuest(Guest guest) {
@Transactional

2022-04-21 17:57 UTC, Spec163 commented on projects/hotel_automation_project/booking_service/src/main/java/nc/unc/ama/booking_service/services/GuestService.java
> +            });
- `@Transactional`
- the method must contain only one `return`
- you can set gouestId to guestUpd obj and use `guestRepo.save(guestUpd)` - if `guestId` is exist than the row will be updated (by guestUpd data), otherwise a new row will be added.

2022-04-21 17:57 UTC, Spec163 commented on projects/hotel_automation_project/booking_service/src/main/java/nc/unc/ama/booking_service/services/GuestService.java
> +            });
- `@Transactional`
- the method must contain only one `return`
- you can set gouestId to guestUpd obj and use `guestRepo.save(guestUpd)` - if `guestId` is exist than the row will be updated (by guestUpd data), otherwise a new row will be added.

2022-04-26 09:19 UTC, kostua16 commented
Проект успешно собрался для коммита ede4a16d28e30ee95eed35fb720e4df2cd165cf0. Разрешение получено.

2022-04-29 12:51 UTC, kostua16 requested changes

2022-04-29 12:51 UTC, kostua16 commented on projects/hotel_automation_project/booking_service/src/main/java/nc/unc/ama/booking_service/controllers/GuestController.java
> +    @DeleteMapping(path="/{guestId)")
) заменить на }

2022-04-29 12:51 UTC, kostua16 commented on projects/hotel_automation_project/booking_service/src/main/java/nc/unc/ama/booking_service/services/GuestService.java
> +    public void deleteGuest(Long guestId) {
добавить `@Transactional`

2022-05-02 19:42 UTC, kostua16 commented
Проект успешно собрался для коммита 32ddc8d58fb34473f6ed6e352157eda88a672404. Разрешение получено.

2022-05-05 13:51 UTC, kostua16 commented
Проект успешно собрался для коммита f9534231511c0eb8c83c09c6d055e626e1d4aedc. Разрешение получено.

2022-05-06 09:21 UTC, closed without merging