feat(BookingService): Booking контролеры, сервисы, репозиторий, entity, DTO #134
kostua16/TLT_NC_AMA_2021 pull request #138
Opened 2022-04-22 11:03 UTC by DcoldD

2022-04-22 11:04 UTC, kostua16 commented
Проект успешно собрался для коммита b400022e81853c26843820b5528fdaf29c104b7e. Разрешение получено.

2022-04-22 11:06 UTC, kostua16 commented
Проект успешно собрался для коммита 87161f8e1f1e2edc1f6b52fbb0ee6af2ec96135b. Разрешение получено.

2022-04-22 13:54 UTC, Spec163 requested changes

2022-04-22 13:54 UTC, Spec163 commented on projects/hotel_automation_project/booking_service/src/main/java/nc/unc/ama/booking_service/services/BookingService.java
> +        return bookingRepo.findById(bookId).get();
check NPE

2022-04-22 13:54 UTC, Spec163 commented on projects/hotel_automation_project/booking_service/src/main/java/nc/unc/ama/booking_service/services/BookingService.java
> +            });
- метод должен содержать только один `return`
- `updatedBooking.setBookId(bookId)`, затем `bookingRepo.save(updatedBooking);`

2022-04-26 09:11 UTC, kostua16 commented
Проект успешно собрался для коммита 2e54285161479d6a88826a0c17122ba5b4c0c58d. Разрешение получено.

2022-05-02 19:59 UTC, kostua16 commented
Проект успешно собрался для коммита 13446b94e764cb6fc973e7b0a8c01e2053929611. Разрешение получено.

2022-05-05 13:51 UTC, kostua16 commented
Проект успешно собрался для коммита b7570be75edaa29d2ac9cd1e442983602f8cc07c. Разрешение получено.

2022-05-06 09:21 UTC, kostua16 commented
Проект успешно собрался для коммита 21d068cff3bb9ecf1d01d8359332c78324642942. Разрешение получено.

2022-05-06 13:55 UTC, kostua16 approved these changes

2022-05-06 15:16 UTC, kostua16 commented
После коммита defa2c32fb2d85e4a549022e508c8956c3efa12b проект невозможно собрать. Разрешение отозвано, требуются исправления.

2022-05-06 16:02 UTC, kostua16 commented
Проект успешно собрался для коммита 2dfb6b82f8a73be164bd40fba4b9cd2f003074a8. Разрешение получено.

2022-05-06 16:03 UTC, kostua16 commented
Проект успешно собрался для коммита 2dfb6b82f8a73be164bd40fba4b9cd2f003074a8. Разрешение получено.

2022-05-06 16:05 UTC, merged