feat(Gateway): Новый модуль для HotelAutomationProject #52
kostua16/TLT_NC_AMA_2021 pull request #76
Opened 2022-03-07 19:37 UTC by DcoldD

2022-03-07 19:38 UTC, kostua16 commented
Проект успешно собрался для коммита 41a1d5442417fdc5a56be63a6b2d5b97381677d0. Разрешение получено.

2022-03-07 19:39 UTC, kostua16 commented
Проект успешно собрался для коммита 870b97138140fa4d886e91d071261b7ead183894. Разрешение получено.

2022-03-09 10:21 UTC, Spec163 commented on projects/hotel_automation_project/discovery_evr/src/main/java/nc/unc/ama/discovery_evr/DiscoveryEvrApplication.java
> +@Configuration
configuration should be moved to a separate class

2022-03-09 10:23 UTC, Spec163 commented on projects/hotel_automation_project/gateway/src/main/resources/application.yml
> +      defaultZone: http://localhost:8761/eureka/eureka/
better use env variable and condition

2022-03-11 08:32 UTC, kostua16 commented
Проект успешно собрался для коммита cc522623678fc9949a22f0d08de39187d0761ddd. Разрешение получено.

2022-03-16 14:29 UTC, Fiyri44 commented on projects/hotel_automation_project/gateway/src/main/resources/application.yml
> +  port: 8765
env

2022-03-16 14:29 UTC, Fiyri44 commented on projects/hotel_automation_project/gateway/src/main/resources/application.yml
> +  port: 8765
Пример ${EUREKA_URI:http://localhost:8761/eureka/eureka/}

2022-03-17 16:52 UTC, kostua16 commented
Проект успешно собрался для коммита 745585bb45603279909b5992c393c07c350831c2. Разрешение получено.

2022-03-18 06:19 UTC, Fiyri44 requested changes
OK

2022-03-18 14:44 UTC, Fiyri44 approved these changes

2022-03-18 14:44 UTC, merged