feat: Новый модуль Booking Service для задачи #54
kostua16/TLT_NC_AMA_2021 pull request #80
Opened 2022-03-09 13:26 UTC by Derrainn

2022-03-09 13:27 UTC, kostua16 commented
Проект успешно собрался для коммита 8ba4aa595926ed836c9036ea95e87239f5da4a0f. Разрешение получено.

2022-03-09 13:28 UTC, kostua16 commented
Проект успешно собрался для коммита 8ba4aa595926ed836c9036ea95e87239f5da4a0f. Разрешение получено.

2022-03-09 13:58 UTC, Spec163 commented on projects/hotel_automation_project/booking_service/src/main/java/nc/unc/ama/booking_service/controllers/GuestControllerImpl.java
> +public class GuestControllerImpl {
empty controller

2022-03-09 14:03 UTC, Spec163 commented on projects/hotel_automation_project/booking_service/src/main/java/nc/unc/ama/booking_service/services/RegistrationService.java
> +        return registrationRepo.findById(registrationId).get();
Check NPE. Method findById() may return empty result.

2022-03-11 13:34 UTC, kostua16 commented
Проект успешно собрался для коммита 71456f5fa47806de27ff8050eaa4c3e351a91d9c. Разрешение получено.

2022-03-11 14:21 UTC, DcoldD requested changes

2022-03-11 14:21 UTC, DcoldD commented on projects/hotel_automation_project/booking_service/src/main/java/nc/unc/ama/booking_service/controllers/PaymentControllerImpl.java
> +
Нотация RestController

2022-03-11 14:21 UTC, DcoldD commented on projects/hotel_automation_project/booking_service/src/main/java/nc/unc/ama/booking_service/repositories/OccupiedRoomsRepo.java
> +
Анотация @Repository

2022-03-11 14:21 UTC, DcoldD commented on projects/hotel_automation_project/booking_service/src/main/java/nc/unc/ama/booking_service/repositories/RegistrationRepo.java
> +
Анотация @Repository

2022-03-11 14:21 UTC, DcoldD commented on projects/hotel_automation_project/booking_service/src/main/java/nc/unc/ama/booking_service/services/RegistrationService.java
> +        return registrationRepo.findById(registrationId).get();
Результат заменить на (ResponseEntity<Registration>), 
get заменить на getOrElse()

2022-03-11 14:45 UTC, kostua16 commented
Проект успешно собрался для коммита 71456f5fa47806de27ff8050eaa4c3e351a91d9c. Разрешение получено.

2022-03-11 14:46 UTC, kostua16 commented
Проект успешно собрался для коммита 71456f5fa47806de27ff8050eaa4c3e351a91d9c. Разрешение получено.

2022-04-06 14:48 UTC, kostua16 commented
Проект успешно собрался для коммита 14c16fd7eb4b6671d669eb564b353a6b3980808b. Разрешение получено.

2022-04-06 14:58 UTC, kostua16 approved these changes

2022-04-06 15:03 UTC, kostua16 commented on projects/hotel_automation_project/booking_service/src/main/java/nc/unc/ama/booking_service/repositories/OccupiedRoomsRepo.java
> +
#111

2022-04-06 15:03 UTC, kostua16 commented on projects/hotel_automation_project/booking_service/src/main/java/nc/unc/ama/booking_service/repositories/OccupiedRoomsRepo.java
> +
#111

2022-04-06 15:04 UTC, kostua16 commented on projects/hotel_automation_project/booking_service/src/main/java/nc/unc/ama/booking_service/repositories/RegistrationRepo.java
> +
#111

2022-04-06 15:05 UTC, kostua16 commented
Проект успешно собрался для коммита ebc429a259412eb55905bbe502b29ded3017f3a9. Разрешение получено.

2022-04-06 15:06 UTC, merged